use std::{collections::BTreeSet, path::PathBuf};

use crate::courses::{
    course::{Coord, Course},
    course_list::CourseList,
};

pub fn make_mk8d(mut saves_dir: PathBuf) -> CourseList {
    let list = BTreeSet::from([
        Course::new(1, Coord::new(3, 1, 4), "Wii  Coconut Mall"),
        Course::new(2, Coord::new(3, 5, 4), "Wii  Maple Treeway"),
        Course::new(3, Coord::new(2, 1, 1), "Wii  Moo Moo Meadows"),
        Course::new(4, Coord::new(4, 3, 4), "MK8  Squeaky Clean Sprint"),
        Course::new(5, Coord::new(2, 4, 1), "DS   Tick Tock Clock"),
        Course::new(6, Coord::new(3, 6, 2), "DS   Peach Gardens"),
        Course::new(7, Coord::new(4, 3, 3), "Wii  Moonview Highway"),
        Course::new(8, Coord::new(4, 1, 3), "Wii  DK Summit"),
        Course::new(9, Coord::new(2, 5, 3), "MK8  Ice Ice Outpost"),
        Course::new(10, Coord::new(3, 5, 3), "3DS  Rock Rock Mountain"),
        Course::new(11, Coord::new(2, 3, 2), "GCN  Sherbet Land"),
        Course::new(12, Coord::new(3, 4, 4), "MK8  Sky-High Sundae"),
        Course::new(13, Coord::new(1, 3, 1), "MK8  Sunshine Airport"),
        Course::new(14, Coord::new(3, 3, 4), "DS   Waluigi Pinball"),
        Course::new(15, Coord::new(2, 4, 4), "N64  Rainbow Road"),
        Course::new(16, Coord::new(4, 6, 4), "Wii  Rainbow Road"),
        Course::new(17, Coord::new(4, 4, 3), "Wii  Koopa Cape"),
        Course::new(18, Coord::new(2, 3, 3), "3DS  Music Park"),
        Course::new(19, Coord::new(2, 3, 4), "N64  Yoshi Valley"),
        Course::new(20, Coord::new(3, 4, 3), "Wii  Mushroom Gorge"),
        Course::new(21, Coord::new(1, 3, 4), "MK8  Mount Wario"),
        Course::new(22, Coord::new(1, 4, 1), "MK8  Cloudtop Cruise"),
        Course::new(23, Coord::new(2, 1, 4), "N64  Toad's Turnpike"),
        Course::new(24, Coord::new(1, 3, 3), "MK8  Electrodrome"),
        Course::new(25, Coord::new(3, 2, 2), "DS   Shroom Ridge"),
        Course::new(26, Coord::new(3, 6, 4), "3DS  Rainbow Road"),
        Course::new(27, Coord::new(2, 5, 1), "Wii  Wario's Gold Mine"),
        Course::new(28, Coord::new(3, 3, 3), "N64  Kalimari Desert"),
        Course::new(29, Coord::new(4, 5, 3), "Wii  Daisy Circuit"),
        Course::new(30, Coord::new(4, 3, 2), "GCN  Daisy Cruiser"),
        Course::new(31, Coord::new(3, 2, 3), "GBA  Sky Garden"),
        Course::new(32, Coord::new(1, 4, 3), "MK8  Bowser's Castle"),
        Course::new(33, Coord::new(3, 2, 4), "Tour Ninja Hideaway"),
        Course::new(34, Coord::new(2, 6, 4), "MK8  Big Blue"),
        Course::new(35, Coord::new(1, 2, 2), "MK8  Toad Harbor"),
        Course::new(36, Coord::new(1, 5, 4), "MK8  Mute City"),
        Course::new(37, Coord::new(2, 6, 3), "MK8  Super Bell Subway"),
        Course::new(38, Coord::new(4, 5, 2), "GCN  DK Mountain"),
        Course::new(39, Coord::new(1, 1, 4), "MK8  Thwomp Ruins"),
        Course::new(40, Coord::new(4, 6, 2), "3DS  Rosalina's Ice World"),
        Course::new(41, Coord::new(1, 6, 3), "MK8  Wild Woods"),
        Course::new(42, Coord::new(4, 1, 4), "MK8  Yoshi's Island"),
        Course::new(43, Coord::new(2, 4, 2), "3DS  Piranha Plant Slide"),
        Course::new(44, Coord::new(2, 1, 3), "DS   Cheep Cheep Beach"),
        Course::new(45, Coord::new(2, 5, 4), "MK8  Hyrule Circuit"),
        Course::new(46, Coord::new(2, 4, 3), "Wii  Grumble Volcano"),
        Course::new(47, Coord::new(1, 5, 3), "MK8  Dragon Driftway"),
        Course::new(48, Coord::new(1, 4, 4), "MK8  Rainbow Road"),
        Course::new(49, Coord::new(3, 6, 3), "Tour Merry Mountain"),
        Course::new(50, Coord::new(2, 2, 4), "3DS  DK Jungle"),
        Course::new(51, Coord::new(3, 1, 2), "3DS  Toad Circuit"),
        Course::new(52, Coord::new(1, 3, 2), "MK8  Dolphin Shoals"),
        Course::new(53, Coord::new(4, 2, 3), "GCN  Waluigi Stadium"),
        Course::new(54, Coord::new(1, 1, 2), "MK8  Water Park"),
        Course::new(55, Coord::new(2, 2, 3), "N64  Royal Raceway"),
        Course::new(56, Coord::new(4, 2, 1), "Tour Bangkok Rush"),
        Course::new(57, Coord::new(1, 2, 3), "MK8  Twisted Mansion"),
        Course::new(58, Coord::new(3, 4, 2), "GBA  Snow Land"),
        Course::new(59, Coord::new(1, 6, 4), "MK8  Animal Crossing Circuit"),
        Course::new(60, Coord::new(4, 5, 4), "MK8  Piranha Plant Cove"),
        Course::new(61, Coord::new(2, 6, 2), "GBA  Ribbon Road"),
        Course::new(62, Coord::new(4, 6, 1), "Tour Madrid Drive"),
        Course::new(63, Coord::new(4, 2, 4), "Tour Singapore Speedway"),
        Course::new(64, Coord::new(4, 6, 3), "SNES Bowser's Castle 3"),
        Course::new(65, Coord::new(4, 4, 4), "Tour Vancouver Velocity"),
        Course::new(66, Coord::new(1, 5, 2), "MK8  Excitebike Arena"),
        Course::new(67, Coord::new(1, 2, 4), "MK8  Shy Guy Falls"),
        Course::new(68, Coord::new(1, 1, 3), "MK8  Sweet Sweet Canyon"),
        Course::new(69, Coord::new(3, 3, 1), "Tour New York Minute"),
        Course::new(70, Coord::new(1, 1, 1), "MK8  Mario Kart Stadium"),
        Course::new(71, Coord::new(4, 4, 2), "GBA  Sunset Wilds"),
        Course::new(72, Coord::new(4, 5, 1), "Tour Rome Avanti"),
        Course::new(73, Coord::new(3, 6, 1), "Tour Berlin Byways"),
        Course::new(74, Coord::new(4, 1, 2), "GBA  Riverside Park"),
        Course::new(75, Coord::new(2, 5, 2), "SNES Rainbow Road"),
        Course::new(76, Coord::new(3, 1, 1), "Tour Paris Promenade"),
        Course::new(77, Coord::new(1, 2, 1), "MK8  Mario Circuit"),
        Course::new(78, Coord::new(2, 1, 2), "GBA  Mario Circuit"),
        Course::new(79, Coord::new(3, 3, 2), "SNES Mario Circuit 3"),
        Course::new(80, Coord::new(4, 2, 2), "DS   Mario Circuit"),
        Course::new(81, Coord::new(3, 5, 2), "GBA  Boo Lake"),
        Course::new(82, Coord::new(2, 2, 1), "GCN  Dry Dry Desert"),
        Course::new(83, Coord::new(4, 3, 1), "Tour Athens Dash"),
        Course::new(84, Coord::new(3, 1, 3), "N64  Choco Mountain"),
        Course::new(85, Coord::new(2, 2, 2), "SNES Donut Plains 3"),
        Course::new(86, Coord::new(4, 4, 1), "Tour Los Angeles Laps"),
        Course::new(87, Coord::new(4, 1, 1), "Tour Amsterdam Drift"),
        Course::new(88, Coord::new(1, 4, 2), "MK8  Bone Dry Ruins"),
        Course::new(89, Coord::new(3, 5, 1), "Tour London Loop"),
        Course::new(90, Coord::new(2, 6, 1), "3DS  Neo Bowser City"),
        Course::new(91, Coord::new(2, 3, 1), "DS   Wario Stadium"),
        Course::new(92, Coord::new(1, 5, 1), "GCN  Yoshi's Circuit"),
        Course::new(93, Coord::new(1, 6, 1), "GCN  Baby Park"),
        Course::new(94, Coord::new(3, 4, 1), "Tour Sydney Sprint"),
        Course::new(95, Coord::new(3, 2, 1), "Tour Tokyo Blur"),
        Course::new(96, Coord::new(1, 6, 2), "GBA  Cheese Land"),
    ]);

    saves_dir.push("mk8d.json");
    CourseList::new_with_list(saves_dir, list)
}
